name: Spotify Now Playing

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Spotify status
        uses: novatorem/novatorem@v0.9.0
        with:
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          commit_message: "Update Spotify status"
